import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import WhatsAppButton from '@/app/componet/WhatsApp/WhatsAppButton';
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoCar",
  description: "Generated by create next app - AI Powered Car Assistant  🚗",
  icons : {
    icon: "https://www.workshop.pk/wp-content/uploads/2020/02/workshop-mechanic-service-lahore-icon-15.png",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Toaster position="top-right" />
          {children}
            {/* ✅ WhatsApp Floating Button (Every Page) */}
        <WhatsAppButton />
        </ReduxProvider>
      </body>
    </html>
  );
}
